spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: test
    password: test
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  devtools:
    livereload:
      enabled: true